from TrainingGov import TrainingGovAPI, Organisations, TrainingComponents
from pprint import pprint
import json

api = TrainingGovAPI("WebService.Read", "Asdf098")

orgs = TrainingComponents()
rto = Organisations()
# search = orgs.search(qualification=True)
# print(search.Results.TrainingComponentSummary.__len__())
# print(dir(search.Results.TrainingComponentSummary[0]))
# print(type(search.Results.TrainingComponentSummary[0]))
# print(search.Results.TrainingComponentSummary[0])
# print(type(search.Results))
# print(dir(search.Results))

# print("#####################################################")
# # # Passing RTO Code
# results = orgs.getDetails("ACMACR401A")
results = orgs.getDetails("RUV04")
# pprint(results)
print('response', results['response'])
print('MappingInformation', results['response'].MappingInformation.Mapping[0].Code)
# print('Classifications', dir(results['response']))
# print('code', results['response'].Code)
# print('ComponentType', results['response'].ComponentType)
# print('Contacts', results['response'].Contacts)
# print('CreatedDate', results['response'].CreatedDate)
# print('CurrencyStatus', results['response'].CurrencyStatus)
# print('DataManagers', results['response'].DataManagers)
# print('IsLegacyData', results['response'].IsLegacyData)
# print('IscOrganisationCode', results['response'].IscOrganisationCode)
# print('MappingInformation', results['response'].MappingInformation)
# print('UsageRecommendations', results['response'].UsageRecommendations.UsageRecommendation[0].StartDate)
# print('UsageRecommendations', type(results['response'].UsageRecommendations.UsageRecommendation[0].StartDate))
# print('UpdatedDate', results['response'].UpdatedDate)
# print('Title', results['response'].Title)
# print('ReverseMappingInformation', results['response'].ReverseMappingInformation)
# print('Releases', results['response'].Releases.Release[1])
# print('Releases sort', results['response'].Releases.Release)
# print('type Releases', type(results['response'].Releases.Release[0]))
# print('len Releases', len(results['response'].Releases.Release[0]))
# print('dir Releases [1]', dir(results['response'].Releases.Release[0]))
# print('dir Releases', dir(results['response'].Releases.Release))
# print('dir Releases[response]', dir(results['response']))
# print(dir(results))

# print("#####################################################")
# result_rto = rto.getCourseList('41558')
# print(result_rto)
